### ISSUE TITLE
Testing face detection

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/OpenCV_Server#14]
# What?
Standardized test video(s) for testing purposes 

## Sub-issues

- [x] Check out other examples of it being done, and locate videos that could be used
- [x] Face Detection Case Study for Accuracy 
- [x] Face Detection Case Study for Efficiency
- [x] Compare C++ and Pyhon
- [x] Compare dlib vs opencv

## Sources

- [A Complete Guide of Facial Recognition Test](https://www.51testing.cc/blog/a-complete-guide-of-facial-recognition-test.html)
- [Using a Light Meter for flawless exposure in your video](https://www.youtube.com/watch?v=s3LSkaSxELw)

**Comment by KjetilIN** [comment]
> Face Detection Case Study for Accuracy
See PR #11

**Comment by marhjoh** [comment]
# Update 03/31/2023 1 PM

Located some videos that can be used. Setup is explained [here](https://github.com/vitay/YouTubeFacesDB), and the official website is [here](https://www.cs.tau.ac.il/~wolf/ytfaces/). 

`The data set contains 3,425 videos of 1,595 different people. All the videos were downloaded from [YouTube](http://www.youtube.com/). An average of 2.15 videos are available for each subject. The shortest clip duration is 48 frames, the longest clip is 6,070 frames, and the average length of a video clip is 181.3 frames.`

**Comment by KjetilIN** [comment]
# Update 03/31/2024

Started working on a case study for efficacy. Here is the numbers so far:

![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/d6611d21-6fe2-435f-913c-2d09c1de2780)

### Issues: 

- It takes ca. 10 minutes to process one video (one iteration of all frames testing all methods) 
- Presenting FPS data as bar chart or as line chart. ( Line chart could be messy but could be cooler)

Here is a sample bar graph: 


![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/9744cb9a-c853-4bc8-92e9-29ac48fbb665)

**Comment by marhjoh** [comment]
@KjetilIN how does the numbers for HoG make sense? I'm thinking about the first image, not the graphs.

**Comment by KjetilIN** [comment]
> @KjetilIN how does the numbers for HoG make sense? I'm thinking about the first image, not the graphs.


The numbers are in the graphs mocks. Not real numbers. Just testing the graphs for now. Will run them at the end of the day.

**Comment by marhjoh** [comment]
@KjetilIN ye, but I'm not thinking about the graphs. HoG should run faster than Haar, which should run faster than DNN. The image after **[Here is the numbers so far: ...]**

**Comment by KjetilIN** [comment]
> @KjetilIN ye, but I'm not thinking about the graphs. HoG should run faster than Haar, which should run faster than DNN. The image after **[Here is the numbers so far: ...]**

Yes, weird. We will see the average after running through all the videos. For now only 6. 

I am thinking about creating a github workflow for compiling the cases. Then we can trigger it and let it work through the night :)

**Comment by KjetilIN** [comment]
# Update: 

Working on setting up workflows for executing and saving Jupiter notebooks. If this work, we can maybe install bigger datasets, and let them run over night. Anyways, both of the types of face detection measurement cases are setup. All I need to do is to improve the comments. This will be done in PR #16. 

Been working for a long time on setting up a workflow file for running the jupyterhub project. However, it takes time to run through and debug. But by the end of the day. It will be correct, we will be able to use it for running both cases. Here is an overview of all the jobs needed: 


![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/e4376caf-3f0d-4fac-9190-a2e17668ade6)

**Comment by marhjoh** [comment]
@KjetilIN I think this would be a good way of representing the data 

![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/94908112/514314b9-643f-459c-86cf-8751d49313f7)

**Comment by KjetilIN** [comment]
# Closing the Issue - update:

Started the Github Action before heading to bed. It was done in the morning. A PR was created #18,  It looks good, some mistakes. However, I had to rewrite where the dataset came from.Thought it came from a good dataset source. 

I fixed some comments and code, but it was a success.Running a new workflow, and when it is finished I will add it as an appendix. Below are some of the sample data that was generated: 



![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/caf95880-9ae9-4066-b661-21afa3d3096a)



![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/0d242e02-a251-41bc-ba35-f025fbcf1021)


![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/c6f5569e-1235-4fdb-bdb7-139f4688420a)



![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/4050cad1-e6ae-4014-8114-fef20d82d8a2)

**Comment by KjetilIN** [comment]
It takes 3 hours to run the workflow, but it is consistent now: 

![Image](https://github.com/RIT-NTNU-Bachelor/OpenCV_Server/assets/66110094/e1f60579-3044-4c37-b0bc-99ec11f74378)
